quotes_json = {
  "vanilla": [
    "CHINA DON'T CARE.",
    "Blocked.",
    "BLOCKED.",
    "You don't have to go home, but you can't stay here.",
    "I am the hat judge. Show me a hat and I will tell you if it's a good hat or bad hat.",
    "I can't believe this was actually allowed to be released to people.",
    "Jeff, I have a question. Why do we keep doing this?",
    "Infinite beards.",
    "I always get run over from behind.",
    "At first I cringe, but I want more.",
    "Walk the cow through a warm room, and then bring it to my plate.",
    "I hate socks.",
    "No one should ever put clothes on a shark.",
    "I've got a salty mustache.",
    "I did not say, \"uh, uh, uh, uh, uh.\"",
    "You know, up until the part where you died, I thought you were having a pretty good run there.",
    "I hate Game Room so much.",
    "It's like I'm in a techno womb.",
    "I feel like I'm gonna throw up, but in a good way.",
    "This Quick Look is over!",
    "Hit the golf button.",
    "The Kool-Aid Man never had a flamethrower.",
    "What PopCap game do you think the Master Chief would like the most?",
    "You need to spit on it first.",
    "I try not to affiliate myself with Canadians.",
    "I don't believe in wheels.",
    "I am the street!",
    "I want a game that is nothing but kicking dumpsters at enemies.",
    "I'm an old man. I like turns.",
    "Hey e3 maybe stop farting for 5 seconds.",
    "I've been a party to many, many stupid things in my life. This is by far the stupidest.",
    "Why not just say KAIJU BATTLE ROBOT JOX?",
    "Oh, Dennis Leary is in this for no good reason.",
    "Let's play some meat!",
    "This is skin-peelingly bad.",
    "I'm gonna no scope these crops.",
    "Don't buy a racing wheel!",
    "You are history's greatest monster.",
    "Because the Dutch are cheap.",
    "You locked eyes with Elmo, that's a mistake.",
    "I've got a salty mustache.",
    "Seattle is actually Spanish for \"taco.\"",
    "You are looking for far too much logical consistency.",
    "Penguins are dope.",
    "The laziest dubstep is arguably the best dubstep.",
    "You're just anti-people-believing-in-things.",
    "Why anything about gelatinous cubes?",
    "Can we enhance this?",
    "They called us \"charmingly garrulous\", which I couldn't think of a more New Yorker thing to describe us as.",
    "There's a lot of face and neck stabbing, if you like to stab dudes in the face and neck.",
    "You can't feed your friend's leg to a robot.",
    "Socks are like feet pants.",
    "Goku's like the Huell Howser of anime.",
    "It's dumb, but its not transcendentally dumb.",
    "Gimme that horsey sauce.",
    "That dude now knows the contours of my body better than I do.",
    "Gardener! What a perfect masseur name!",
    "The day spa is the ultimate high-stakes \"is this a public space it's OK to be naked in?\" scenario.",
    "Timmy, you're not a converted Primal Rage arcade cabinet, Timmy! You're a stupid dog!",
    "It's the Giant Barmcast!",
    "How weird is the existence of the Christmas tree farmer?",
    "Sheep are incredibly muscular.",
    "Well, you're trying to get her pregnant, right?",
    "Caused all this collateral damage with my F-bombs.",
    "I was dressed up like a pizza delivery guy; brought this F-bomb instead.",
    "This podcast is over."
  ],

  "explicit": [
    "You are a human piece of shit.",
    "I didn't come here to get harassed by asshole teenagers, I get enough of that as it is.",
    "Exécutable? What the fuck are you saying!?",
    "I'm going to ride my fucking resentment into a fucking volcano!",
    "You're talking about sex, right?",
    "I'm a dick, and I want to subject other people to that.",
    "Let me put my hot blade inside you.",
    "I want you to go to hell.",
    "John McTiernan, master of modern fucking action movies. The man made Predator, god dammit! If you're gonna sit there and tell me Renny Harlin made a better movie than him, you are all assholes and I don't want to work with you anymore!",
    "Suck on it, Ron Weasley.",
    "I'm just gonna say it, if you get shit on a carrot, you just throw it away. Don't even try to salvage that carrot.",
    "Hold on to your fucking hats, gentlemen.",
    "I could talk about Peter Molyneux's balls for a long time.",
    "There's nothing I'd rather talk about right now than Peter Molyneux's balls!",
    "He's like the J.R.R. Tolkien of being shitty.",
    "Fuck you, Brad Garrett! I hope you burn in hell!",
    "Fuck your milk!",
    "My dick doesn't have tits.",
    "Fuck you and your medicine ball!",
    "It's 18 years old, Daytona USA. You could fuck it if you wanted to.",
    "This is the result of trying to touch butts.",
    "I can play Simon Says like a motherfucker.",
    "Fuck your box!!",
    "I just magic'd in my pants.",
    "They're basically sperm.",
    "THESE ARE SHEETS FOR FUCKING IN.",
    "You people are abject porn monsters.",
    "YO THOSE ARE FUCKING DOUBLE-UNDERLINE SICK.",
    "I WILL CONTINUE TO CALL PAX AUSTRALIA PAXA UNTIL IT FUCKING CATCHES ON.",
    "This is like a fuckin' Woody Allen heist going on here.",
    "Take that you shitty wizard.",
    "It makes me angry how fucking much I enjoy this game.",
    "No, there’s nothing I'd rather talk about right now than Peter Molyneux's balls.",
    "Don't milk a hippie.",
    "Fuckin' helicopters are the worst! They're trying to kill you as you get in them.",
    "I want to straddle that horsey sauce. I would ride it straight to Hell!"
  ]
}