quotes_json = {
	"vanilla": [
		"CHINA DON'T CARE.",
		"Blocked.",
		"BLOCKED.",
		"You don't have to go home, but you can't stay here.",
		"I am the hat judge. Show me a hat and I will tell you if it's a good hat or bad hat.",
		"I can't believe this was actually allowed to be released to people.",
		"Jeff, I have a question. Why do we keep doing this?",
		"Infinite beards.",
		"I always get run over from behind.",
		"At first I cringe, but I want more.",
		"Walk the cow through a warm room, and then bring it to my plate.",
		"I hate socks.",
		"No one should ever put clothes on a shark.",
		"I've got a salty mustache.",
		"I did not say, \"uh, uh, uh, uh, uh.\"",
		"You know, up until the part where you died, I thought you were having a pretty good run there.",
		"I hate Game Room so much.",
		"It's like I'm in a techno womb.",
		"I feel like I'm gonna throw up, but in a good way.",
		"This Quick Look is over!",
		"Hit the golf button.",
		"The Kool-Aid Man never had a flamethrower.",
		"What PopCap game do you think the Master Chief would like the most?",
		"You need to spit on it first.",
		"I try not to affiliate myself with Canadians.",
		"I don't believe in wheels.",
		"I am the street!",
		"I want a game that is nothing but kicking dumpsters at enemies.",
		"I'm an old man. I like turns.",
		"Hey e3 maybe stop farting for 5 seconds.",
		"I've been a party to many, many stupid things in my life. This is by far the stupidest.",
		"Why not just say KAIJU BATTLE ROBOT JOX?",
		"Oh, Dennis Leary is in this for no good reason."
	],

	"explicit": [
		"You are a human piece of shit.",
		"I didn't come here to get harassed by asshole teenagers, I get enough of that as it is.",
		"Exécutable? What the fuck are you saying!?",
		"I'm going to ride my fucking resentment into a fucking volcano!",
		"You're talking about sex, right?",
		"I'm a dick, and I want to subject other people to that.",
		"Let me put my hot blade inside you.",
		"I want you to go to hell.",
		"John McTiernan, master of modern fucking action movies. The man made Predator, god dammit! If you're gonna sit there and tell me Renny Harlin made a better movie than him, you are all assholes and I don't want to work with you anymore!",
		"Suck on it, Ron Weasley.",
		"I'm just gonna say it, if you get shit on a carrot, you just throw it away. Don't even try to salvage that carrot.",
		"Hold on to your fucking hats, gentlemen.",
		"I could talk about Peter Molyneux's balls for a long time.",
		"There's nothing I'd rather talk about right now than Peter Molyneux's balls!",
		"He's like the J.R.R. Tolkien of being shitty.",
		"Fuck you, Brad Garrett! I hope you burn in hell!",
		"Fuck your milk!",
		"My dick doesn't have tits.",
		"Fuck you and your medicine ball!",
		"It's 18 years old, Daytona USA. You could fuck it if you wanted to.",
		"This is the result of trying to touch butts.",
		"I can play Simon Says like a motherfucker.",
		"Fuck your box!!",
		"I just magic'd in my pants.",
		"They're basically sperm.",
		"THESE ARE SHEETS FOR FUCKING IN",
		"You people are abject porn monsters.",
		"YO THOSE ARE FUCKING DOUBLE-UNDERLINE SICK.",
		"I WILL CONTINUE TO CALL PAX AUSTRALIA PAXA UNTIL IT FUCKING CATCHES ON."
	]
}