quotes_json = {
  "vanilla": [
    "CHINA DON'T CARE.",
    "Blocked.",
    "BLOCKED.",
    "You don't have to go home, but you can't stay here.",
    "I am the hat judge. Show me a hat and I will tell you if it's a good hat or bad hat.",
    "I can't believe this was actually allowed to be released to people.",
    "Jeff, I have a question. Why do we keep doing this?",
    "Infinite beards.",
    "I always get run over from behind.",
    "At first I cringe, but I want more.",
    "Walk the cow through a warm room, and then bring it to my plate.",
    "I hate socks.",
    "No one should ever put clothes on a shark.",
    "I've got a salty mustache.",
    "I did not say, \"uh, uh, uh, uh, uh.\"",
    "You know, up until the part where you died, I thought you were having a pretty good run there.",
    "I hate Game Room so much.",
    "It's like I'm in a techno womb.",
    "I feel like I'm gonna throw up, but in a good way.",
    "This Quick Look is over!",
    "Hit the golf button.",
    "The Kool-Aid Man never had a flamethrower.",
    "What PopCap game do you think the Master Chief would like the most?",
    "You need to spit on it first.",
    "I try not to affiliate myself with Canadians.",
    "I don't believe in wheels.",
    "I am the street!",
    "I want a game that is nothing but kicking dumpsters at enemies.",
    "I'm an old man; I like turns.",
    "Hey E3, maybe stop farting for five seconds.",
    "I've been a party to many, many stupid things in my life. This is by far the stupidest.",
    "Why not just say KAIJU BATTLE ROBOT JOX?",
    "Oh, Dennis Leary is in this for no good reason.",
    "Let's play some meat!",
    "This is skin-peelingly bad.",
    "I'm gonna no scope these crops.",
    "Don't buy a racing wheel!",
    "You are history's greatest monster.",
    "Because the Dutch are cheap.",
    "You locked eyes with Elmo, that's a mistake.",
    "I've got a salty mustache.",
    "Seattle is actually Spanish for \"taco.\"",
    "You are looking for far too much logical consistency.",
    "Penguins are dope.",
    "The laziest dubstep is arguably the best dubstep.",
    "You're just anti-people-believing-in-things.",
    "Why anything about gelatinous cubes?",
    "Can we enhance this?",
    "They called us \"charmingly garrulous\", which I couldn't think of a more New Yorker thing to describe us as.",
    "There's a lot of face and neck stabbing, if you like to stab dudes in the face and neck.",
    "You can't feed your friend's leg to a robot.",
    "Socks are like feet pants.",
    "Goku's like the Huell Howser of anime.",
    "It's dumb, but its not transcendentally dumb.",
    "Gimme that horsey sauce.",
    "Gardener! What a perfect masseur name!",
    "Timmy, you're not a converted Primal Rage arcade cabinet, Timmy! You're a stupid dog!",
    "It's the Giant Barmcast!",
    "How weird is the existence of the Christmas tree farmer?",
    "Sheep are incredibly muscular.",
    "Well, you're trying to get her pregnant, right?",
    "Caused all this collateral damage with my F-bombs.",
    "I was dressed up like a pizza delivery guy; brought this F-bomb instead.",
    "This podcast is over.",
    "Only usable on grilled cheese sandwiches. That is the only application of Kraft Singles as far as I'm concerned.",
    "So you want a Hot Pocket with more pocket and less hot, is that what you're saying?",
    "There's too much stuff inside this Hot Pocket.",
    "You could put a GoPro on a bear pretty easy.",
    "The cops are here for the crimes against video games you've committed, Sonic.",
    "We need more downtempo grooves. These are neither downtempo nor groovy enough tunes.",
    "So this is a parable for communism.",
    "Moral of the story here is do not make any sort of accords with laser-shooting wolves.",
    "Best original music!",
    "I want it on this table.",
    "I would fight a dolphin.",
    "I'd have to train to fight a dolphin; I wouldn't just jump out there and start fighting a dolphin.",
    "My forehead hasn't grown with the rest of my body.",
    "She's reading your mind with her scary eyes.",
    "I've never blinked because I have no eyelids!",
    "Harry Potter and the 9/11 Conspiracy.",
    "YOU'RE RIGHT IT IS THE TAKING CARE OF BUSINESS GUYS!",
    "Buckner and Garcia wrote us a song. This is it.",
    "On death, all hummingbirds explode.",
    "Did you know? Babies can't eat Legos. Fact.",
    "You're carrying around a Lego baby, Gary. Where's the real baby?",
    "Brad values pixel density above perhaps just about anything else.",
    "Everyone's so obsessed with the Link thing, no one ever asks, like, is that the same Mario every time?",
    "Explain Baby Mario.",
    "Show me a mommy Mario.",
    "You're saying pipes don't have rights?",
    "No rights for pipes, no rights for pipes...",
    "You're banned, you're banned, you're Nintendo banned!",
    "Are you talking about a different kind of chocolate fountain, here?",
    "And Space Pope himself, Mr. Patrick Klepek.",
    "I've got milk that's older than him. I should probably throw out that milk.",
    "No one had to eat any legs on Saturday, so that was good.",
    "Jeff, can I ask you a serious question? Why do we keep doing this?",
    "Wait, something kinda funky in Game Room? Balderdash!",
    "I like that this is where we're at on Game Room: not even games that were good enough to be put out.",
    "You know what, Jeff? If you were a man, you'd be wearing a hat right now.",
    "I hate Game Room. I hate it. I actively hate it. I hate sitting on the couch with you and looking at these stupid games.",
    "I'm not gonna eat a supernatural anything.",
    "It's sad that I lost my leg, but let's not let it go to waste.",
    "Let's put our frowns on upside down, and eat my buddy's leg.",
    "I hate watching you drink warm soda. It's bad for you and it's bad for the soda.",
    "No one gets that reference. I barely get that reference.",
    "Once you hit 30 you can't do shots.",
    "We're trying to make the brown tone over here.",
    "This is a terrible conversation.",
    "You are Bathroom Guy.",
    "You're just jealous of other peoples' hot news.",
    "Video games are bad; discuss.",
    "Prove that video games are good.",
    "I played Ms. Pac-Man. It's pretty good. I decided this weekend that it's about communism.",
    "I have a problematic toilet.",
    "Alright, now I'm not gonna wash my hands, and I'm gonna take these cookies.",
    "Good Old Raisins and Peanuts! GORP! You guys never heard of GORP?",
    "I'm gonna give myself an award for Best Statement of the Year for that."
  ],

  "explicit": [
    "This is what sadomasochism will look like in the future.",
    "I will pay good money to see you as a dirty sexual predator.",
    "That dude now knows the contours of my body better than I do.",
    "The day spa is the ultimate high-stakes \"is this a public space it's OK to be naked in?\" scenario.",
    "Are Depends real? Are adult diapers real?",
    "Yeah, you like getting it both ways, don't you?",
    "Being in the tub with someone else's poop, there are few things that are just as sheer terrible.",
    "Being there, and then all of the sudden, poop floats up, hits the surface.",
    "Too much in your wet diaper?",
    "Who knows what direction that poop is gonna take.",
    "Just the tips, though?",
    "Now that wolf is gonna fuck that pig.",
    "It's just like, a little fleshy sliver there.",
    "He's making meth.",
    "Dolphins are tough! Dolphins can fuck you up.",
    "Jam something in its blowhole.",
    "Vinny, you and I both, crazy Potterheads. It's like potheads, but for Harry Potter.",
    "Just gonna masturbate under my invisible cloak, don't mind me.",
    "You are a human piece of shit.",
    "I didn't come here to get harassed by asshole teenagers, I get enough of that as it is.",
    "Exécutable? What the fuck are you saying!?",
    "I'm going to ride my fucking resentment into a fucking volcano!",
    "You're talking about sex, right?",
    "I'm a dick, and I want to subject other people to that.",
    "Let me put my hot blade inside you.",
    "I want you to go to hell.",
    "John McTiernan, master of modern fucking action movies. The man made Predator, god dammit! If you're gonna sit there and tell me Renny Harlin made a better movie than him, you are all assholes and I don't want to work with you anymore!",
    "Suck on it, Ron Weasley.",
    "I'm just gonna say it, if you get shit on a carrot, you just throw it away. Don't even try to salvage that carrot.",
    "Hold on to your fucking hats, gentlemen.",
    "I could talk about Peter Molyneux's balls for a long time.",
    "There's nothing I'd rather talk about right now than Peter Molyneux's balls!",
    "He's like the J.R.R. Tolkien of being shitty.",
    "Fuck you, Brad Garrett! I hope you burn in hell!",
    "Fuck your milk!",
    "My dick doesn't have tits.",
    "Fuck you and your medicine ball!",
    "It's 18 years old, Daytona USA. You could fuck it if you wanted to.",
    "This is the result of trying to touch butts.",
    "I can play Simon Says like a motherfucker.",
    "Fuck your box!!",
    "I just magic'd in my pants.",
    "They're basically sperm.",
    "THESE ARE SHEETS FOR FUCKING IN.",
    "You people are abject porn monsters.",
    "YO THOSE ARE FUCKING DOUBLE-UNDERLINE SICK.",
    "I WILL CONTINUE TO CALL PAX AUSTRALIA PAXA UNTIL IT FUCKING CATCHES ON.",
    "This is like a fuckin' Woody Allen heist going on here.",
    "Take that you shitty wizard.",
    "It makes me angry how fucking much I enjoy this game.",
    "No, there’s nothing I'd rather talk about right now than Peter Molyneux's balls.",
    "Don't milk a hippie.",
    "Fuckin' helicopters are the worst! They're trying to kill you as you get in them.",
    "I want to straddle that horsey sauce. I would ride it straight to Hell!",
    "Give me access to your members-only site of hot mommy Marios.",
    "Why is that hill sentient? That's fucked up, that shouldn't be like that. What's a hill think about?",
    "You can't out-engineer a fucking chainsaw.",
    "You diseased piece of shit.",
    "I fuckin' love Game Room. What a piece of shit. What an incredible, half-assed piece of garbage this is.",
    "Oh, you asshole.",
    "Go to hell.",
    "This is boring as shit.",
    "Oh yeah, Game Room! What shit is happening this week?",
    "Oh, don't front, Jeff. You were already pooping your pants before we even started recording.",
    "Fine day to shit yourself, while recording a podcast.",
    "It's easy to piss off Batman. Doesn't take much.",
    "You fucking people. You listening, if you're the person who's like, 'Oh, Sonic the Hedgehog in 2D, finally,' fuck you, alright? You're part of the problem.",
    "We were talking about furries and yiffing and GenCon.",
    "I am not smart enough to know what any of that shit means.",
    "Sometimes there are cuts where you don't expect them to be. I'm talking about your butthole.",
    "I don't think getting buffalo sauce on your ass would feel particularly good regardless.",
    "Can we agree that buffalo sauce on your asshole would not feel good?",
    "If I didn't have to sit here and keep monitoring this podcast, I would leave too, at hearing such an audaciously bullshit statement.",
    "Can I ask you why you're saying 'booty'?",
    "I already live in a world without Batman and it fucking suuuucks.",
    "You know what's not the new sweat? Hitler.",
    "You know what makes a game better? Hitler.",
    "Those penguins are shitting Pong balls. Or, snow balls. Or I guess shit balls, is what they are."
  ]
}
